web:
  build: ./node

nginx:
  restart: always
  image: nginx
  ports:
    - "8081:80"
  volumes:
    - "./nginx/:/var/log/nginx"
    - "./nginx/nginx.conf:/etc/nginx/nginx.conf"
  links:
    - web:web
