web:
  build: ./node
  ports:
    - "8080:3000"

nginx:
  restart: always
  image: nginx
  ports:
    - "80:80"
  volumes:
    - "./nginx/:/var/logs/nginx"
    - "./nginx/nginx.conf:/etc/nginx/nginx.conf"
  links:
    - web:web
